"use strict";

module.exports = {
  USE_WOTB6: false,
  MIN_WILLMEMBERS_UPDATE_FREQ: 180,
  MIN_MEMBERS_UPDATE_FREQ: 180,
	STEP_COUNT_MIN: 4,
	STEP_COUNT_MAX: 150,
	MIN_CACHE_UPDATE_FREQ: 150 // 2 min 30 (150 sec)
};