export const MonitConstants = {
  USE_WOTB6: false,
  DEFAULT_LANGUAGE: "fr",
  MIN_WILLMEMBERS_UPDATE_FREQ: 180,
  MIN_MEMBERS_UPDATE_FREQ: 180,
	STEP_COUNT_MIN: 4,
	STEP_COUNT_MAX: 150,
  MIN_CACHE_UPDATE_FREQ: 150, // 2 min 30 (150 sec)
  MIN_WOT_QUALITY_CACHE_UPDATE_FREQ: 300,
  QUALITY_CACHE_ACTION : {
    GET_QUALITY: 0,
    GET_MEANS: 1,
    INIT: 2,
    GET_SENTRIES_COUNT: 3,
    GET_D_SEN: 3
  }
};
